kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lwfw-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem