apiVersion: v2
name: ibm-b2bi-prod
version: 0.1.0
appVersion: 1.2.16
description: IBM Secure File Gateway 6.2.0.0
dependencies:
  - name: service-account
    version: 0.5.0
    repository: https://charts.cloudnativetoolkit.dev
  - name: ibm-sfg-b2bi-6-2
    version: 2.1.3
    repository: https://therayy.github.io/operators-instances