apiVersion: v1
kind: Secret
metadata:
  name: itxa-oracle-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "210"
type: Opaque
stringData:
  databaseName: ORCL
  dbUser: dbuser018
  dbPassword: XXXX2023
  dbHostIp: "9.X0.X5.23X"
  dbPort: "1521"
  accessKey: "cec21c22b36046a3a11a83bdc62b5aa6"
  secretKey: "c08a464a98e5b487b4e9617a39a1028345d9019802e3c1d2"
  dbCurrentSchema: "dbuser018"