apiVersion: v1
kind: Secret
metadata:
  name: itxa-mssql-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "210"
type: Opaque
stringData:
  databaseName: dbsql
  dbUser: sa
  dbPassword: Newpc4us
  dbHostIp: "9.3X.26X.9X"
  dbPort: "1433"
  accessKey: "cec21c22b36046a3a1bdcccc62b5aa6"
  secretKey: "c08a464a98e5b487b4e9617xxxa1028345d9019802e3c1d2"
