kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  name: ibm-b2bi-rolebinding-b2bi-prod
  namespace: b2bi-prod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b2bi-prod
roleRef:
  kind: Role
  name: ibm-b2bi-role-b2bi-prod
  apiGroup: rbac.authorization.k8s.io